language: ruby
rvm:
  - 2.2
install:
  - bundle install --retry=3
before_install:
  - sudo apt-get update
  - sudo apt-get install dbus
  - sudo apt-get install at-spi2-core
  - sudo apt-get install libgirepository1.0-dev gobject-introspection
  - sudo apt-get install gir1.2-atspi-2.0 libatk-adaptor
  - sudo apt-get install libgtk-3-dev libatk1.0-dev libatspi2.0-dev
  - sudo service dbus restart
script: "xvfb-run dbus-launch bundle exec rake test"
