language: ruby
rvm:
  - 2.2
install:
  - bundle install --retry=3
before_install:
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev gobject-introspection
  - sudo apt-get install gir1.2-atspi-2.0 libatk-adaptor
  - sudo apt-get install libgtk-3-dev libatk1.0-dev libatspi2.0-dev
  - sudo apt-get install dbus
before_script:
  - "ps -Af"
script: "xvfb-run bundle exec rake test"
